env:
   global:
     - CONAN_USERNAME: "conan"
     - CONAN_LOGIN_USERNAME: "conanbot"
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/conan-community/conan"
     - CONAN_STABLE_BRANCH_PATTERN: "master"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "master"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "2.7.10"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=lasote/conangcc49-i386
      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
