linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86
      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
